---
name: Assignment 3 Github Workflow - Terraform

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Check Terraform Format
        run: terraform fmt -recursive -check
        continue-on-error: false

      